name: CI/CD for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run Django Test Cases
      run: |
        cd altius
        python manage.py check_table_locking_changes api
