name: Check Required Files

on: [push, pull_request]

jobs:
  check-required-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script to check required files
        run: |
          chmod +x ./scripts/check_required_files.sh
          ./scripts/check_required_files.sh
