name: Count Files

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run count_files.sh script
        id: count_files
        run: |
          chmod +x ./scripts/count_files.sh
          FILE_COUNT=$(./scripts/count_files.sh .)
          echo "file_count=${FILE_COUNT}" >> $GITHUB_ENV

      - name: Comment on PR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="No of Files in the Root Directory: ${{ env.file_count }}"
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
