name: Generate Changelog

on:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run generate_changelog.sh script
        id: generate_changelog
        run: |
          chmod +x ./scripts/generate_changelog.sh
          ./scripts/generate_changelog.sh

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog [skip ci]"
          git push
        # if: github.ref == 'refs/heads/main' # Only push changes on the main branch