name: Increment Version

on:
  push:
    branches:
      - main
      - dev

jobs:
  increment-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Increment version
      run: |
        chmod +x ./scripts/increment_version.sh
        ./scripts/increment_version.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Increment version"
        git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}