name: Increment Version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Increment version
      run: |
        chmod +x ./scripts/increment_version.sh
        ./scripts/increment_version.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Increment version"
        git push